/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package bankingmanagementsystem;

import java.awt.Color;
import java.awt.Image;
import java.io.IOException;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.ImageIcon;
import javax.swing.JProgressBar;
import javax.swing.UIManager;

/**
 *
 * @author Muhammad Asad
 */
public class LoadingScreen extends javax.swing.JFrame implements Runnable{

    /**
     * Creates new form LoadingScreen
     * @throws java.lang.InterruptedException
     */

    Thread th;
    String accNo;
    public LoadingScreen(String accNo) throws InterruptedException {
        initComponents();
        Image menuIcon = new ImageIcon(this.getClass().getResource("/asset/icons/menuIcon.png")).getImage();
        this.setIconImage(menuIcon);
        this.accNo  = accNo;
        th = new Thread((Runnable)this);
        UIManager.put( "nimbusOrange", new Color( 37, 56, 235 ) );
 
        
    }
    public void startLoading(){
        setVisible(false);
        th.start();
    }
    @Override
    public void run(){
        try {
            for (int i = 0; i <= 100; i++) {
            int maximumValue = jProgressBar1.getMaximum();
            int currentValue = jProgressBar1.getValue();
            if (currentValue < maximumValue) {
                jProgressBar1.setValue(jProgressBar1.getValue() + 1);
            }else{
                
                setVisible(false);
                Main mainObject = new Main(accNo);
                mainObject.setVisible(true);
                break;        
            }
            Thread.sleep(25); 
        }
           
        } catch (InterruptedException e) {
        }
    }
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jProgressBar1 = new javax.swing.JProgressBar();
        loadingName = new javax.swing.JLabel();
        loading = new javax.swing.JLabel();
        walpaper = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Banking Management System");
        setBounds(new java.awt.Rectangle(0, 0, 0, 0));
        setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        setLocation(new java.awt.Point(0, 0));
        setResizable(false);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jProgressBar1.setBackground(new java.awt.Color(255, 255, 255));
        jProgressBar1.setForeground(new java.awt.Color(51, 51, 51));
        jProgressBar1.setCursor(new java.awt.Cursor(java.awt.Cursor.WAIT_CURSOR));
        jProgressBar1.setStringPainted(true);
        jProgressBar1.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                jProgressBar1StateChanged(evt);
            }
        });
        jPanel1.add(jProgressBar1, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 414, 560, 20));

        loadingName.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/icons/loading.gif"))); // NOI18N
        jPanel1.add(loadingName, new org.netbeans.lib.awtextra.AbsoluteConstraints(280, 200, 110, 80));

        loading.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        loading.setForeground(new java.awt.Color(255, 255, 255));
        loading.setText("Loading ....");
        jPanel1.add(loading, new org.netbeans.lib.awtextra.AbsoluteConstraints(320, 290, -1, -1));

        walpaper.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asset/images/landing_page_template_2_2508.jpg"))); // NOI18N
        jPanel1.add(walpaper, new org.netbeans.lib.awtextra.AbsoluteConstraints(-120, 0, 840, 470));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void jProgressBar1StateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_jProgressBar1StateChanged
        
    }//GEN-LAST:event_jProgressBar1StateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException | InstantiationException | IllegalAccessException | javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(LoadingScreen.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(() -> {
            try {
                new LoadingScreen("").setVisible(true);
            } catch (InterruptedException ex) {
                Logger.getLogger(LoadingScreen.class.getName()).log(Level.SEVERE, null, ex);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel jPanel1;
    private javax.swing.JProgressBar jProgressBar1;
    private javax.swing.JLabel loading;
    private javax.swing.JLabel loadingName;
    private javax.swing.JLabel walpaper;
    // End of variables declaration//GEN-END:variables
}
